"""empty message

Revision ID: 12081636ae05
Revises: b46792b86009
Create Date: 2020-06-14 12:55:33.983886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12081636ae05'
down_revision = 'b46792b86009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_point', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('errors')
    # ### end Alembic commands ###
