"""empty message

Revision ID: aca537460fb3
Revises: 12081636ae05
Create Date: 2020-06-14 13:04:17.551330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca537460fb3'
down_revision = '12081636ae05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errors', sa.Column('error', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('errors', 'error')
    # ### end Alembic commands ###
